[package]
name = "mode-s"
version = "0.1.0"
authors = ["wcampbell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deku = "0.12.0"

[dev-dependencies]
hex = "0.4.2"
hexlit = "0.4.0"
assert_hex = "0.2"
