[workspace]
members = ["apps", "libadsb_deku", "rsadsb_common"]
exclude = ["ensure_no_std"]
resolver = "2"

[workspace.package]
rust-version = "1.74.0"
license = "MIT"
edition = "2021"

[profile.release]
strip = true
overflow-checks = true
